export const letters = [
  {
    number: 0,
    upperCase: 'A',
    lowerCase: 'a',
    isSpecial: false,
  },
  {
    number: 1,
    upperCase: 'Á',
    lowerCase: 'á',
    isSpecial: false,
  },
  {
    number: 2,
    upperCase: 'B',
    lowerCase: 'b',
    isSpecial: false,
  },
  {
    number: 3,
    upperCase: 'D',
    lowerCase: 'd',
    isSpecial: false,
  },
  {
    number: 4,
    upperCase: 'E',
    lowerCase: 'e',
    isSpecial: false,
  },
  {
    number: 5,
    upperCase: 'F',
    lowerCase: 'f',
    isSpecial: false,
  },
  {
    number: 6,
    upperCase: 'G',
    lowerCase: 'g',
    isSpecial: false,
  },
  {
    number: 7,
    upperCase: 'Ǵ',
    lowerCase: 'ǵ',
    isSpecial: false,
  },
  {
    number: 8,
    upperCase: 'H',
    lowerCase: 'h',
    isSpecial: false,
  },
  {
    number: 9,
    upperCase: 'X',
    lowerCase: 'x',
    isSpecial: false,
  },
  {
    number: 10,
    upperCase: 'Í',
    lowerCase: 'ı',
    isSpecial: false,
  },
  {
    number: 11,
    upperCase: 'I',
    lowerCase: 'i',
    isSpecial: false,
  },
  {
    number: 12,
    upperCase: 'J',
    lowerCase: 'j',
    isSpecial: false,
  },
  {
    number: 13,
    upperCase: 'K',
    lowerCase: 'k',
    isSpecial: false,
  },
  {
    number: 14,
    upperCase: 'Q',
    lowerCase: 'q',
    isSpecial: false,
  },
  {
    number: 15,
    upperCase: 'L',
    lowerCase: 'l',
    isSpecial: false,
  },
  {
    number: 16,
    upperCase: 'M',
    lowerCase: 'm',
    isSpecial: false,
  },
  {
    number: 17,
    upperCase: 'N',
    lowerCase: 'n',
    isSpecial: false,
  },
  {
    number: 18,
    upperCase: 'Ń',
    lowerCase: 'ń',
    isSpecial: false,
  },
  {
    number: 19,
    upperCase: 'O',
    lowerCase: 'o',
    isSpecial: false,
  },
  {
    number: 20,
    upperCase: 'Ó',
    lowerCase: 'ó',
    isSpecial: false,
  },
  {
    number: 21,
    upperCase: 'P',
    lowerCase: 'p',
    isSpecial: false,
  },
  {
    number: 22,
    upperCase: 'R',
    lowerCase: 'r',
    isSpecial: false,
  },
  {
    number: 23,
    upperCase: 'S',
    lowerCase: 's',
    isSpecial: false,
  },
  {
    number: 24,
    upperCase: 'T',
    lowerCase: 't',
    isSpecial: false,
  },
  {
    number: 25,
    upperCase: 'U',
    lowerCase: 'u',
    isSpecial: false,
  },
  {
    number: 26,
    upperCase: 'Ú',
    lowerCase: 'ú',
    isSpecial: false,
  },
  {
    number: 27,
    upperCase: 'V',
    lowerCase: 'v',
    isSpecial: false,
  },
  {
    number: 28,
    upperCase: 'W',
    lowerCase: 'w',
    isSpecial: false,
  },
  {
    number: 29,
    upperCase: 'Y',
    lowerCase: 'y',
    isSpecial: false,
  },
  {
    number: 30,
    upperCase: 'Z',
    lowerCase: 'z',
    isSpecial: false,
  },
  {
    number: 31,
    upperCase: 'Sh',
    lowerCase: 'sh',
    isSpecial: true,
  },
  {
    number: 32,
    upperCase: 'C',
    lowerCase: 'c',
    isSpecial: false,
  },
  {
    number: 33,
    upperCase: 'Ch',
    lowerCase: 'ch',
    isSpecial: true,
  },
]
